import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata: Metadata = {
  title: 'Tost Notification',
  description: 'Generated by @gyanaranjans',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang='en' suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <div
              className='h-screen w-screen flex items-center justify-center 
         dark:bg-gray-800 dark:text-white bg-white text-black'
            >
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
